### ISSUE TITLE
transform() got an unexpected keyword argument 'path_sam'

### ISSUE THREAD

**Issue by zpashkutz** [akikuno/DAJIN2#151]
### 📋 Description

While trying to process samples in either batch or single sample mode, an error message keeps popping up related to 'path_sam' in midsv.transform step. I am uncertain why this occurs, my request works in version 0.7.4 but not in version 0.8.0 or 0.9.0. 

I tried changing the path name of the directory with the files various different ways including no spaces and default naming that is exported from Oxford nanopore barcoding (ie barcode01). None of these change the behavior.

### 🔖 DAJIN2 Version (Optional)

0.8.0 and 0.9.0

### ⚠️ Error message (Optional)

2026-02-26 12:49:32, ERROR, An unexpected error occurred at DAJIN_Results/.gui_upload/ver0-9-0_022626/upload/sample
Traceback (most recent call last):
  File "/root/miniconda/envs/env-dajin2/lib/python3.10/site-packages/DAJIN2/utils/multiprocess.py", line 99, in target
    suppress_stderr(function, arg)
  File "/root/miniconda/envs/env-dajin2/lib/python3.10/site-packages/DAJIN2/utils/multiprocess.py", line 42, in suppress_stderr
    function(*args, **kwargs)
  File "/root/miniconda/envs/env-dajin2/lib/python3.10/site-packages/DAJIN2/core/core.py", line 145, in execute_sample
    preprocess.generate_midsv(ARGS, is_control=False, is_sv=False)
  File "/root/miniconda/envs/env-dajin2/lib/python3.10/site-packages/DAJIN2/core/preprocess/alignment/midsv_caller.py", line 244, in generate_midsv
    midsv_chaind = transform_to_midsv_format(path_best_sam)
  File "/root/miniconda/envs/env-dajin2/lib/python3.10/site-packages/DAJIN2/core/preprocess/alignment/midsv_caller.py", line 84, in transform_to_midsv_format
    return midsv.transform(path_sam=path_sam, qscore=False, keep={"FLAG"})
TypeError: transform() got an unexpected keyword argument 'path_sam'

### 🔍 Environment (Optional)

```markdown
OS: Ubuntu 22.04
Python version: 3.12.3
```

**Comment by akikuno** [comment]
@zpashkutz

Thanks for reporting the issue.
I suspect it’s due to an outdated version of `midsv`, a dependency of DAJIN2.

Could you please remove your current virtual environment (or create a new one) and reinstall DAJIN2?

Here are the commands to recreate the `env-dajin2` environment:

```bash
conda deactivate
conda remove -y -n env-dajin2 --all
conda create -y -n env-dajin2 -c conda-forge -c bioconda python=3.12 DAJIN2
conda activate env-dajin2
```

After reinstalling, the versions should look like this (DAJIN2 `0.9.0` and `midsv` `0.13.1`):

```bash
conda list -n env-dajin2 | grep -e dajin2 -e midsv
## packages in environment at /home/kuno/miniforge/envs/test-dajin2:
# dajin2                    0.9.0              pyhdfd78af_0    bioconda
# midsv                     0.13.1             pyhdfd78af_0    bioconda
```

I think this should resolve the issue.
Could you try it and let me know if it works?
